import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const contentDir = path.join(root, 'content', 'topics');
const publicDir = path.join(root, 'public');

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function page({ title, body }) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light dark; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    body { max-width: 880px; margin: 0 auto; padding: 32px 20px; line-height: 1.6; }
    header, article, section { margin-bottom: 32px; }
    a { color: #2563eb; }
    .meta, .tags, footer { color: #666; font-size: 0.95rem; }
    .card { border: 1px solid #ddd; border-radius: 12px; padding: 20px; margin: 16px 0; }
    code { background: rgba(127,127,127,.15); padding: 0.1rem 0.25rem; border-radius: 4px; }
  </style>
</head>
<body>
${body}
<footer>Generated by Dev Blog.</footer>
</body>
</html>
`;
}

async function readJson(file) {
  return JSON.parse(await readFile(file, 'utf8'));
}

function assertPost(post, file) {
  for (const key of ['id', 'topic', 'title', 'date', 'summary', 'sections']) {
    if (!post[key]) throw new Error(`${file}: missing required field ${key}`);
  }
  if (!Array.isArray(post.sections)) throw new Error(`${file}: sections must be an array`);
}

async function loadTopics() {
  const topicIds = await readdir(contentDir);
  const topics = [];

  for (const topicId of topicIds) {
    const topicPath = path.join(contentDir, topicId);
    const topic = await readJson(path.join(topicPath, 'topic.json'));
    const postsDir = path.join(topicPath, 'posts');
    const postFiles = (await readdir(postsDir)).filter((file) => file.endsWith('.json'));
    const posts = [];

    for (const postFile of postFiles) {
      const fullPath = path.join(postsDir, postFile);
      const post = await readJson(fullPath);
      assertPost(post, fullPath);
      posts.push(post);
    }

    posts.sort((a, b) => b.date.localeCompare(a.date));
    topics.push({ ...topic, posts });
  }

  topics.sort((a, b) => a.title.localeCompare(b.title));
  return topics;
}

function renderPostLink(post) {
  return `<li><a href="/posts/${escapeHtml(post.id)}.html">${escapeHtml(post.title)}</a> <span class="meta">${escapeHtml(post.date)}</span><br>${escapeHtml(post.summary)}</li>`;
}

function renderSources(sources = []) {
  if (!sources.length) return '';
  return `<section><h2>Sources</h2><ul>${sources.map((source) => `<li><a href="${escapeHtml(source.url)}">${escapeHtml(source.title)}</a></li>`).join('\n')}</ul></section>`;
}

async function build() {
  const topics = await loadTopics();

  await rm(publicDir, { recursive: true, force: true });
  await mkdir(path.join(publicDir, 'topics'), { recursive: true });
  await mkdir(path.join(publicDir, 'posts'), { recursive: true });

  const home = page({
    title: 'Dev Blog',
    body: `<header><h1>Dev Blog</h1><p>AI-assisted development newsletters for engineering topics.</p></header>
<section><h2>Topics</h2><ul>${topics.map((topic) => `<li><a href="/topics/${escapeHtml(topic.slug)}.html">${escapeHtml(topic.title)}</a><br>${escapeHtml(topic.description)}</li>`).join('\n')}</ul></section>`
  });
  await writeFile(path.join(publicDir, 'index.html'), home);

  for (const topic of topics) {
    const topicHtml = page({
      title: `${topic.title} - Dev Blog`,
      body: `<header><p><a href="/index.html">← Dev Blog</a></p><h1>${escapeHtml(topic.title)}</h1><p>${escapeHtml(topic.description)}</p></header>
<section><h2>Posts</h2><ul>${topic.posts.map(renderPostLink).join('\n')}</ul></section>`
    });
    await writeFile(path.join(publicDir, 'topics', `${topic.slug}.html`), topicHtml);

    for (const post of topic.posts) {
      const postHtml = page({
        title: `${post.title} - Dev Blog`,
        body: `<article>
<p><a href="/topics/${escapeHtml(topic.slug)}.html">← ${escapeHtml(topic.title)}</a></p>
<h1>${escapeHtml(post.title)}</h1>
<p class="meta">${escapeHtml(post.date)} · ${escapeHtml(topic.title)}</p>
<p><strong>${escapeHtml(post.summary)}</strong></p>
<p class="tags">${(post.tags || []).map((tag) => `#${escapeHtml(tag)}`).join(' ')}</p>
${post.sections.map((section) => `<section><h2>${escapeHtml(section.heading)}</h2><p>${escapeHtml(section.body)}</p></section>`).join('\n')}
${renderSources(post.sources)}
</article>`
      });
      await writeFile(path.join(publicDir, 'posts', `${post.id}.html`), postHtml);
    }
  }

  console.log(`Built ${topics.length} topic(s) and ${topics.reduce((count, topic) => count + topic.posts.length, 0)} post(s) into public/`);
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});
